# 数据库敏感信息
DB_USERNAME: root
DB_PASSWORD: 4626463ljh.w


#RabbitMq
RABBITMQ_USERNAME: admin
RABBITMQ_PASSWORD: admin123
#智谱api
ZHIPU_API_KEY: ec61cdc428ab45fa820f9e97ac117b98.e6YtTosYuIKJCyDw
#qdrant
QDRANT_API_KEY: 123456
#Minio
MINIO_USERNAME: minioadmin
MINIO_PASSWORD: minioadmin

#Redis
REDIS_PASSWORD: 4626463ljh.w


#Linux地址
LINUX_HOST: 192.168.100.132

#mail
SPRING_USERNAME: 2950355750@qq.com